#!/bin/bash

DIRECTORY="/opt/git-repos"
declare -a lx_repos=( `find $DIRECTORY/leadx/ -maxdepth 1 -type d -exec basename {} \;` )
declare -a mt_repos=( `find $DIRECTORY/mt/ -maxdepth 1 -type d -exec basename {} \;` )

for each_repo in ${lx_repos[@]:1} ; do
  echo -e "\e[32;1m$each_repo\e[0m"
  cd "$DIRECTORY/leadx/$each_repo"
  git pull
done
for each_repo in ${mt_repos[@]:1} ; do
  echo -e "\e[31;1m$each_repo\e[0m"
  cd "$DIRECTORY/mt/$each_repo"
  git pull
done
exit 0
